### ISSUE TITLE
Last snap update was almost a year ago

### ISSUE THREAD

**Issue by dwvisser** [muesli/duf#171]
I want the latest, so I will have to remove the snap install I currently use, and go with the latest appropriate release file. See https://snapcraft.io/duf-utility

**Comment by muesli** [comment]
Thanks for the heads up @dwvisser. Due to snap's sandbox limitations `duf` can't access the required information from the system any longer. A few months back I actually tried removing it from the snap store altogether, but apparently that didn't work. I just tried once again. Can you verify it's not showing up in the snap store any longer?

**Comment by dwvisser** [comment]
I just confirmed that. Thanks!

BTW, the latest .deb worked great for me. (I wanted the ability to filter on mount point.)

**Comment by muesli** [comment]
Thank you for verifying! There's also an official Debian package in unstable now, so hopefully it will eventually also trickle down to the Ubuntu derivatives.

**Comment by muesli** [comment]
Oh, indeed looks like there's some progress: https://packages.ubuntu.com/impish/duf

**Comment by dwvisser** [comment]
I’m actually on latest Ubuntu. I'll stick with your .deb for now, because the Impish package is on a version too old to support the feature I wanted. Thanks!

Objective Reality - there for you whether or not you're a subscriber.
________________________________
