### ISSUE TITLE
"permission denied" on Ubuntu 18.04 with LXD installed using Snap

### ISSUE THREAD

**Issue by clement-analogue** [muesli/duf#21]
On my LXD server, installed using Snap, `duf` first output are errors

```
/var/snap/lxd/common/ns/shmounts: permission denied
/var/snap/lxd/common/ns/mntns: permission denied
```

The rest of the output is fine.

![duf_lxd](https://user-images.githubusercontent.com/1931507/94202126-654c6180-febd-11ea-8888-9e8092dd1f75.png)

The relevant part of `/proc/self/mountinfo` is

```
764 92 0:117 / /var/snap/lxd/common/ns rw,relatime - tmpfs tmpfs rw,size=1024k,mode=700
778 764 0:3 mnt:[4026532660] /var/snap/lxd/common/ns/shmounts rw - nsfs nsfs rw
751 764 0:3 mnt:[4026532657] /var/snap/lxd/common/ns/mntns rw - nsfs nsfs rw
```

Edit: It is `duf` commit 02d3baceb58df0e08d10f5f685232e215974ef4a but it was already the case when I tried yesterday.

**Comment by muesli** [comment]
That's very odd, as we specifically check for permission errors since 798aeb67d82efd6096d9cefe2f1d5a5176e7a1c0. Since you even mention a specific commit you're running on, I wouldn't usually ask you to do this... but since I can't see any way these errors could slip through, can you double-check you're really running the right revision/version here? For example, does `--inodes` work with this one?

**Comment by clement-analogue** [comment]
Inodes options is here (but not working ^^)
![duf_inodes](https://user-images.githubusercontent.com/1931507/94242856-ee43b700-ff16-11ea-87ed-3d0aa40adb83.png)
I checkout 798aeb67d82efd6096d9cefe2f1d5a5176e7a1c0 build on Ubuntu 20.04, transferred to my server on Ubuntu 18.04. Same result
![duf_798aeb67d82efd6096d9cefe2f1d5a5176e7a1c0](https://user-images.githubusercontent.com/1931507/94243292-7b870b80-ff17-11ea-87c5-6a84d8f7892e.png)

**Comment by muesli** [comment]
I'm perplex. I guess this must mean this isn't a "real" permission error (by type), but produced from somewhere down the stack. Guess we'll have to catch this by "string" 🤔

**Comment by simos** [comment]
I entered here because I saw _snap_ in the title. 

I have been testing with creating a snap package for `duf`. I would get those two _permission denied_ errors when I was running the confined (`strict` but allow `home`, `observe-mount`) snap package of `duf`.
Reporter, do you mean that you run the snap package of LXD, or you have created a snap package for duf?

**Comment by muesli** [comment]
As the current snap sandbox is too constrained for a tool like `duf`, the snap package is currently unmaintained. For recent Debian & Ubuntu installs you can simply run `apt install duf` now. Also see #148.
